baseURL = 'https://build-100-websites.fun/'
languageCode = 'en-us'
title = '[2/100] build-100-websites.fun'
theme = 'hugo-plain-theme'

[params]
  custom_css = ["css/simple.css/simple.css", "css/simple-tweaks.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

command = "hugo"